<div>&nbsp;The orbits of the planets are ellipses, with the Sun at one focus of the ellipse.</div>
<div>&nbsp;</div>
<div style="text-align: center;"><img src="userfiles/image/lab3/kepler_08.gif" class="lab" alt="" /></div>
<div>&nbsp;</div>
<div>After a long struggle, in which he tried mightily to avoid his eventual conclusion, Kepler was forced finally to the realization that the orbits of the planets were not the circles demanded by Aristotle and assumed implicitly by Copernicus, but were instead the &quot;flattened circles&quot; that we call ellipses.</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div><span class="violet"><strong>THE BASIC PROPERTIES OF ELLIPSES</strong></span></div>
<div>&nbsp;</div>
<div>1. For an ellipse there are two points called foci (the singular is focus) such that the sum of the distances to the foci from any point on the ellipse is a constant. In terms of the diagram above, with &quot;the black X&quot; marking the location of the foci, we have the equation: x+y=constant that defines the ellipse in terms of the distances x and y.</div>
<div>&nbsp;</div>
<div>2. The amount of &quot;flattening&quot; of the ellipse is termed the eccentricity. A circle may be viewed as a special case of an ellipse with zero eccentricity. As the ellipse becomes more flattened the eccentricity approaches one. Thus, all ellipses have eccentricities lying between zero and one. The orbits of the planets are ellipses but the eccentricities are so small, for most of the planets, that they look circular at first glance. One must measure the geometry carefully to determine that their orbits are not circles, but ellipses of small eccentricity. Pluto and Mercury are exceptions: their orbits are sufficiently eccentric to see that they are not circles.</div>
<div>&nbsp;</div>
<div style="text-align: center;"><img src="userfiles/image/lab3/eccentricity.jpg" class="lab" alt="" /></div>
<div style="text-align: left;">&nbsp;</div>
<div style="text-align: left;">3. The long axis of the ellipse is called the major axis, while the short axis is called the minor axis. Half of the major axis is termed the semimajor axis. The length of the semimajor axis is often termed the radius of the ellipse. It can be shown that the average separation of a planet from the Sun as it goes around its elliptical orbit is equal to the length of the semimajor axis. Thus, by the &quot;radius&quot; of a planet's orbit one usually means the length of the semimajor axis. The semimajor axis is typically labeled &quot;a&quot;.</div>
<div style="text-align: left;">&nbsp;</div>
<div style="text-align: center;"><img src="userfiles/image/lab3/Elipses_03.gif" class="lab" alt="" /></div>
<div>&nbsp;</div>
<div><a onclick="window.open(this.href,'','resizable=yes,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=no,dependent=no,width=520,height=400,left=200,top=50,status'); return false" href="http://physics.unm.edu/101lab/portal/userfiles/html/eccentricity.html" class="applet">Click Here</a> to view the various eccentricities from 0 to 0.9.</div>
<div>&nbsp;</div>
<div>Below is a table with the orbital eccentricity of the eight planets and Pluto.</div>
<div>&nbsp;</div>
<div style="text-align: center;"><img src="userfiles/image/lab3/oribtal-eccentricity.gif" class="lab" alt="" /></div>
<div>&nbsp;</div>
<div>Notice that the Earth's orbit is only slightly elliptical.  You might think the Earth's varying distance from the Sun is responsible for the seasons.  But this effect is very small.  The seasons are due to the Earth being tilted on it's axis.</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>

<div>One hypothesis (idea) for why we have seasons is the varying distance from the Earth to the Sun, the Earth is warmer when it is closer to the Sun (Summer) and colder when the Earth is farther from the Sun (Winter).  However, there are several observations about the seasons and the Earth's motion around the Sun that are inconsistent with this hypothesis. </div> 
<div>&nbsp;</div>

<div>For example, in the Northern Hemisphere (where we live) summer and winter do not occur at the closest (perihelion) and furthest (aphelion) points of the Earth's orbit around the Sun.  In fact, the Earth reaches it's closest point to the Sun in January.</div>
<div>&nbsp;</div>

<div>Also, while the Earth's orbit is elliptical, it's eccentricity is small so it is too circular to produce seasonal changes.</div>
    
    
<div>&nbsp;</div>
<div>[%problem%]</div>

<div>&nbsp;</div>

<div>In fact, the seasons are caused by the 23 degree tilt of the Earth's 24 hour rotation about its axis.  When the northern part of the Earth is tilted towards the Sun, the northern part of the Earth has the Sun higher in the sky giving more intense sunlight and the days are longer.  This causes summer in the Northern hemisphere.  In the winter, the northern hemisphere is tilted away from the Sun, which puts the Sun lower n the Sky (less intense sunlight) and the days are shorter.  This causes winter in the Northern Hemisphere.</div>

<div>&nbsp;</div>

<div>And when the northern hemisphere is tilted towards the Sun, the southern hemisphere is tilted away and vice versa.  This is why Australia has summer when it is winter in Albuquerque and when Australia has winter, we have summer.</div>

<div>&nbsp;</div>

<div><a target="_blank" href="http://www.walter-fendt.de/ph14e/keplerlaw2.htm" class="applet">Try this applet</a>. Select each of the planets and compare their eccentricities. Note the pie shaped &quot;equal areas in equal time&quot; that are being created.</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<p>&nbsp;</p>