<div>Now, instead of measuring the intensity of light bulbs we will use computer simulations to measure the light emitted by stars. In the process we will further explore the inverse square law for light. The interactive photometry exercise allows you to simulate measurements of the brightness of different stars. Each star has a different luminosity. Take about ten measurements each of the most luminous and least luminous star, and one in between. Make sure that you sample distances ranging from 15 to 150 (distance units are arbitrary in this case). When you are done with each star, the graph of the measured intensity (called flux in this case) as a function of distance should look pretty filled in.</div>
<div>&nbsp;</div>
<div><a target="_blank" href="http://jersey.uoregon.edu/vlab/InverseSquare/index.html" class="applet">Click Here</a> for an Interactive Photometry Exercise (courtesy of the University of Oregon).</div>
<div>&nbsp;&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>