<div>The ratio of the squares of the revolutionary periods for two planets is equal to the ratio of the cubes of their semimajor axes</div>
<div>&nbsp;</div>
<div style="text-align: center;"><img alt="" class="lab" src="userfiles/image/lab3/kepler3.jpg" /></div>
<div>&nbsp;</div>
<div>In this equation &quot;P&quot; represents the period of the orbit for a planet and &quot;a&quot; represents the length of its semimajor axis. The subscripts &quot;1&quot; and &quot;2&quot; distinguish quantities for planet 1 and 2 respectively. The period is how much time it takes to do one orbit.  Note that both periods must be in the same time units and both semimajor axis lengths must be in the same distance units.</div>
<div>&nbsp;</div>
<div>Kepler's Third Law implies that the period for a planet to orbit the Sun increases rapidly with the radius of its orbit. Thus, we find that Mercury, the innermost planet, takes only 88 days to orbit the Sun but the distant dwarf planet Pluto requires 248 years to do the same.</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div><a target="_blank" class="applet" href="http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2003%20UB313;orb=1">This applet</a> illustrates Kepler's Third Law and allows you to visualize orbits in the Solar System. Hit the Fast Forward button to start the objects moving. You can view the orbits from any angle using the slide bars at the bottom and right of the animation, and the zoom slide bar allows you to focus on the inner planets, or zoom out to the orbit of the dwarf planet Eris. You can also change the speed of the animation by changing the time increment to 1 month, for example. And you can run it backwards if you want. This graphic illustrates the third law as it applies to the Solar System. Watch how quickly the inner planets move with respect to the   outer planets.</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>Sir Isaac Newton developed an understanding of forces in general and showed that Kepler's Laws can be generalized to apply to all objects moving under the influence of gravity including those outside our own solar system. The ratio of a<span class="ss">3</span> to p<span class="ss">2</span> for objects orbiting our Sun is equal to 1, when a is expressed in AU and p in years. The equation below represents this relationship but says M = a<span class="ss">3</span> / p<span class="ss">2</span>  where M is equal to 1 solar mass or the mass of our Sun. We can find the mass of other stars in units of the Sun's mass using this equation if we know the semi-major axis and periods of the planets that orbit them. M is the total mass of both bodies, star and planet, but the star is usually almost all of the mass.</div>
<div>&nbsp;</div>
<div style="text-align: center;"><img alt="" class="lab" src="userfiles/image/lab3/MPA.jpg" /></div>
<div>&nbsp;</div>
<!-- <div>To calculate for M you first need to find a<span class="ss">3</span>. The cube of 0.052 is 1.4e-4. Then we need P<span class="ss">2</span> . But first we must convert p to years. 4.23 days is equal to 0.0116 years ( 4.23 / 365 ). Now 0.0116 squared is equal to 1.34e-4. So the value for M is 1.4e-4 / 1.34e-4 = 1.04. This tells us that 51 Peg is 1.04 solar masses or almost the same size as our Sun. How about the star Tau Boo? What is its mass in solar masses?</div>
<div>&nbsp;</div> -->
<div>Kepler's Laws apply to all objects moving under the influence of gravity.</div>
<div>&nbsp;</div>
<div>Kepler's third law can be written in the following simple form:</div>
<div>&nbsp;</div>
<div style="text-align: center;"><span class="xlarge"><span class="yellow"><strong>P<span class="ss">2</span>  = a<span class="ss">3</span><br />
</strong></span></span></div>
<div style="text-align: center;"><span class="xlarge"><span class="yellow"><strong>where P is in years and a is in AU</strong></span></span><br />
&nbsp;</div>
<div>&nbsp;</div>
<div>This equation only works for objects which are orbiting the sun.</div>
<div>&nbsp;</div>
<div>Using the above formula and the information from the table below, calculate the semi-major axes of the two asteroids Pallas and Ceres and enter them in the spaces below.</div>
<div>&nbsp;</div>
<table class="table95">
    <tbody>
        <tr>
            <td>Object Name</td>
            <td>Semi-major axis <span class="xxxlarge">a</span> (AU)</td>
            <td>Orbital Period <span class="xxxlarge">P</span> years</td>
        </tr>
        <tr>
            <td>Mercury</td>
            <td>.39</td>
            <td>.24</td>
        </tr>
        <tr>
            <td>Venus</td>
            <td>.72</td>
            <td>.62</td>
        </tr>
        <tr>
            <td>Earth</td>
            <td>1</td>
            <td>1</td>
        </tr>
        <tr>
            <td>Mars</td>
            <td>1.52</td>
            <td>1.88</td>
        </tr>
        <tr>
            <td>Pallas</td>
            <td>[%problem%]</td>
            <td>3.62</td>
        </tr>
        <tr>
            <td>Ceres</td>
            <td>[%problem%]</td>
            <td>4.61</td>
        </tr>
        <tr>
            <td>Jupiter</td>
            <td>5.200</td>
            <td>11.88</td>
        </tr>
        <tr>
            <td>Saturn</td>
            <td>9.54</td>
            <td>29.46</td>
        </tr>
        <tr>
            <td>Uranus</td>
            <td>19.18</td>
            <td>84.07</td>
        </tr>
        <tr>
            <td>Neptune</td>
            <td>30.060</td>
            <td>164.82</td>
        </tr>
        <tr>
            <td>Pluto</td>
            <td>39.44</td>
            <td>248.6</td>
        </tr>
    </tbody>
</table>
<div>&nbsp;</div>
<div>&nbsp;[%problem%]</div>
<div>&nbsp;</div>
<div>Now calculate the cubes of the semi-major axes and the squares of the orbital periods of the planets listed in the table and fill in those spaces in the table. REMEMBER TO ENTER ONLY SIGNIFICANT FIGURES ALLOWED!</div>
<div>&nbsp;</div>
<table class="table95">
    <tbody>
        <tr>
            <td>&nbsp;Object Name</td>
            <td>&nbsp;Semi-major axis <span class="xxxlarge">a</span> (AU)</td>
            <td>Orbital Period <span class="xxxlarge">P</span> (years)</td>
            <td>&nbsp;<span class="xlarge">a</span><span class="ss"><span class="xlarge">3</span></span>(in units of AU<span class="ss">3</span>)</td>
            <td>&nbsp;P<span class="ss">2</span>(in units of years<span class="ss">2</span>)</td>
        </tr>
        <tr>
            <td>&nbsp;Mercury</td>
            <td>&nbsp;.39</td>
            <td>&nbsp;.24</td>
            <td>[%problem%]</td>
            <td>[%problem%]</td>
        </tr>
        <tr>
            <td>&nbsp;Earth</td>
            <td>&nbsp;1</td>
            <td>&nbsp;1</td>
            <td>[%problem%]</td>
            <td>[%problem%]</td>
        </tr>
        <tr>
            <td>&nbsp;Jupiter</td>
            <td>&nbsp;5.200</td>
            <td>&nbsp;11.88</td>
            <td>[%problem%]</td>
            <td>[%problem%]</td>
        </tr>
        <tr>
            <td>&nbsp;Neptune</td>
            <td>&nbsp;30.060</td>
            <td>&nbsp;164.82</td>
            <td>[%problem%]</td>
            <td>[%problem%]</td>
        </tr>
    </tbody>
</table>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>An important application of Newton's generalization of Kepler's third law is being able to determine mass of a central body based on the motion of a satellite around that body.   In order to apply the following equation, the mass of the central body has to be much greater than whatever is orbiting it ( this makes sense - think about the masses of the planets vs. the Sun's mass).<br />
&nbsp;</div>
<div style="text-align: center;"><span class="xxxlarge"><span class="yellow">M = a<span class="ss">3</span>/ P<span class="ss">2</span> </span></span></div>
<div>&nbsp;</div>
<div>Remember that <span class="yellow">a</span> still has to be in AU, <span class="yellow">P</span> in years, and then the mass, <span class="yellow">M</span>, comes out in units of the <span class="yellow">Sun's mass</span>, or <span class="yellow">solar</span> masses.</div>
<div>&nbsp;</div>


<div>[%problem%]</div>
<div>&nbsp;</div>



<div>[%problem%]</div>
<div>&nbsp;</div>
<div>A current topic of great interest in astronomy is the search for extra-solar planets, planets in orbits around other stars.  There are now 1743 confirmed planets with 452 known multi-planet systems and over 4,000 additional exoplanet candidates currently being investigated.  On April 17, 2014, the Kepler telescope discovered the first Earth-size exoplanet in the "Habitable Zone" of another star.  We will discuss how extrasolar planets are detected, in more detail, later in the semester. Right now we will work backwards and use the semi-major axes and periods of some extrasolar planets to determine the masses of their parent stars.</div>
<div>&nbsp;</div>
<div>Let's look at the Interactive Extra-solar Planets Catalog data sheets using this link <a target="_blank" href="http://exoplanet.eu/catalog-all.php">Extra-solar Planets.</a> Find a planet orbiting the star 51 Peg. Click on the word PLANET in the right hand column. This will sort the planets in alphabetical order. Scroll down to 51 Peg. The one planet listed has a semi-major axis of 0.052 AU and a period of 4.23 days.</div>
<div>&nbsp;</div>
<div>Using the <a href="http://exoplanet.eu/catalog-all.php" target="_blank">extrasolar planets link</a>, look at the values for the extrasolar planets around the stars 51 Peg and 47 UMa. Just <strong>scroll down</strong> on that first page of the website to get the information that you need.</div>
<div>&nbsp;</div>
<div>Calculate the masses of the stars, 51 Peg and 47 UMa the same way you calculated the mass of Jupiter above. Enter your answers below:</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<p>&nbsp;</p>