<div>We will now apply what we have learned to a phenomenon that baffled ancient astronomers for many centuries.</div>
<div>&nbsp;</div>
<div>If you watch a planet move across the night sky over many nights, you will notice that it will usually move in an easterly direction with respect to the stars (of course, during the night, everything moves from east to west - we are talking about the planet's motion relative to the stars). However, every so often, the planet will slow down, stop, reverse direction and move in a westerly direction for a while. This westerly motion is called retrograde motion. After a while, the planet will again slow down, stop and then resume its normal easterly motion.</div>
<div>&nbsp;</div>
<div>This retrograde motion was very difficult for early astronomers to explain. Early astronomers believed in a geocentric model of the Solar System. That is, they thought every body in the Solar System orbited around the Earth. According to <a onclick="window.open(this.href,'','resizable=yes,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=no,dependent=no,width=800,height=700,left=150,top=50,status'); return false" href="http://physics.unm.edu/101lab/portal/userfiles/html/Ptolemy.html">Ptolemy's geocentric view</a>, the Earth was the center. The Moon is the next circle out, then Mercury, Venus, the Sun, Mars, Jupiter, Saturn and the outlying stars.</div>
<div>&nbsp;</div>
<div>Copernicus was the first to rediscover an alternative model considered by the ancient Greeks. Copernicus asserted that the bodies in the Solar System did not revolve around us, but instead that the Earth and the other planets revolved around the Sun. This is called a heliocentric model of the Solar System. We now know it to be correct, but when this idea became well known (around 1515) it was considered to be highly unorthodox! In this lab, we will see that if we use the heliocentric model, we can more easily explain the retrograde motion of the planets.</div>
<div>&nbsp;</div>
<div>The Copernican model was still based on circular orbits (and therefore still required further refinement which we can now do with Kepler's Laws -- according to Kepler's first law planets move in elliptical orbits), but with Kepler's improvements it was able to achieve a precision superior to that of the Ptolemaic model. The explanation for retrograde motion in this system is much simpler and more natural arising from the fact that the Earth is moving and that planets further from the sun are moving more slowly in their orbits than those closer to the sun. It is the simple act of overtaking a planet that leads to retrograde motion. The same thing happens when you pass a car on the freeway. The other car seems to move backward with respect to your car. Let us now examine what retrograde motion looks like.</div>
<div>&nbsp;</div>
<div><a href="http://physics.unm.edu/101lab/portal/userfiles/image/lab3/marsmovie.gif" onclick="window.open(this.href+'?sid='+Math.random(),'','resizable=yes,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=no,dependent=no,width=600,height=400,left=200,top=100,status'); return false">Click Here</a> to view an animation of Mars' retrograde motion (courtesy of T. Snow, University of Colorado, Boulder).</div>
<div>&nbsp;</div>
<div>Now we are going to try to understand how the heliocentric model of the solar system helps us understand retrograde motion.</div>
<div>&nbsp;</div>
<div>According to Kepler's Third Law the Earth travels faster in its orbit than do the &quot;superior&quot; planets (all planets outside the Earth's orbit), it overtakes and passes them at times during their mutual orbits around the Sun. As the Earth begins to overtake Mars, for example, Mars will appear to slow its eastward motion among the stars. Then just as the Earth overtakes it, Mars will appear to loop slightly westward for a short time. Once the Earth is well past Mars, Mars resumes its eastward motion among the stars.</div>
<div>&nbsp;</div>
<div>The animation below shows a top-down view of retrograde motion in the Copernican heliocentric system.  Notice how the line draws the path of Mars in the sky as seen from Earth. Now, reverse the situation. If you were on Mars, what path would the line draw against the background stars as Earth moved in it's orbit?</div>
<div>&nbsp;</div>
<div><a href="http://www.mhhe.com/physsci/astronomy/applets/Retro/frame.html" target="_blank" class="applet">Click Here</a> to view a retrograde motion animation where you can view motion from different planets (courtesy of McGraw-Hill Companies, Inc)</div>
<div>&nbsp;</div>
<div><a class="applet" href="http://www.astro.utoronto.ca/~zhu/ast210/both.html" target="_blank">Click Here</a> to view a heliocentric and geocentric retrograde applet (courtesy of the University of Toronto). Notice how complex the orbits would have to be to follow Ptolemy's model of the solar system. (can be slow to load)</div>
<div>&nbsp;</div>
<div>This should give you enough of an idea about retrograde motion to answer the questions for this part of the lab.</div>
<div>&nbsp;</div>
<div style="text-align: center;"><img alt="" class="lab" src="userfiles/image/lab3/copernican-move.gif" /></div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<p>&nbsp;</p>