<div class="darkbox">
<div><strong>3. Determining the Hubble Constant</strong></div>
</div>
<div><br />
<span class="violet"><strong>Using M100 to calculate Hubble's constant</strong></span></div>
<div>&nbsp;</div>
<div>M100 is the galaxy whose distance we found in the last lab.  It is one of the Virgo cluster galaxies.  But Instead of using the recessional velocity of M100 itself, it is more exact to use the recessional velocity of the center of the Virgo cluster. Individual galaxies within the cluster orbit the center of the cluster, so that they have an additional component to the velocity apart from the general movement of the cluster away from us. In other words, whenever a galaxy's motion is affected by a significant source of gravity (such as in a group or a cluster), its recessional velocity is not entirely due to the expansion of  the universe.  Think of a beehive moving away from you.  Each bee has an extra velocity component as it swarms around the receding beehive.  What we want is the net recessional motion of the beehive.<br />
&nbsp;</div>
<div>Huchra et al. (1995) found the recessional velocity of the Virgo cluster to be 1396 km/sec. You already calculated the distance to M100 in the last lab. The most recent value astronomers have found is 17.1 Mpc, so let's use that. Now divide <span class="yellow">v</span> by <span class="yellow">d</span> to obtain the current value of the Hubble constant. Don't forget your units!</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>Does your result agree with what you learned in class, or read in your text?</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div><span class="violet"><strong>Using clusters of galaxies to calculate Hubble's constant</strong></span></div>
<div>&nbsp;</div>
<div>As a comparison, we are going to determine the Hubble constant by plotting the distance and recessional velocity for a number of clusters.</div>
<div>&nbsp;</div>
<div>You will need to calculate the distance to some of the clusters using the Virtual Observatory.</div>
<div>&nbsp;</div>
<ol>
    <li>Go to this <a href="userfiles/html/draghubble.html" onclick="window.open(this.href,'','resizable=yes,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=no,dependent=no,width=1100,height=800,left=25,top=25,status'); return false">Link</a> to plot the data interactively. If you place the cursor over a cluster on the right, you will see its name and two numbers.  The first is the distance to the cluster.  The second is its recessional velocity.  <span class="turq"><strong>Some of the clusters have ?? where the distance should be.</strong></span>  The distances to these clusters we will roughly estimate using the Virtual Observatory (following the instructions on the Problems page).<br />
    &nbsp;</li>
    <li>Plot recessional velocity vs. distance by dragging the galaxy cluster icons onto the grid.<br />
    &nbsp;</li>
    <li>Estimate a best fit line through the points and the origin (you can use a ruler or the edge of a straight piece of paper held against the screen).<br />
    &nbsp;</li>
    <li>Find the slope of the line. The slope represents the Hubble constant. Don't forget your units!</li>
</ol>
<div>&nbsp;</div>
<div>Now that you have two estimates of the Hubble constant, you can estimate the age of the universe!</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div><span class="violet"><strong>Galaxy Cluster Dynamics</strong></span></div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div><span class="violet"><strong>Completing the Hubble Law Graph</strong></span></div>
<div>&nbsp;</div>
<div>To complete the Hubble's Law graph, first roughly calculate the distance to the following clusters (&quot;Use Virtual Observatory&quot;).  You will look at a galaxy in each of the clusters. <span class="yellow">Assume that all the galaxies have the same actual size, 20,000 pc.</span></div>
<div>&nbsp;</div>
<div><a onclick="window.open(this.href,'','resizable=yes,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=no,dependent=no,width=800,height=700,left=100,top=50,status'); return false" href="/Courses/Saul/Images/AngularSizeSummary.gif">CLICK HERE</a> for a refresher on finding angular size and actual size. </div>
<div>&nbsp;</div>
<div>Remember that we use this formula:</div>
<div>&nbsp;</div>
<div style="text-align: center;"><span class="yellow"><span class="xxlarge"><strong>distance 	= 	actual size 	/ 	angular size</strong></span></span></div>
<div style="text-align: center;"><span class="yellow"><span class="xxlarge"><strong><br />
(in pc)&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (in pc) &nbsp;&nbsp;&nbsp; &nbsp; 		(in radians)</strong></span></span></div>
<div style="text-align: center;">&nbsp;</div>

<div><strong>Virtual Observatory settings</strong>
<ul><li>Filter => Red
<li>Image Format => GIF
<li>HEIGHT / WIDTH => 7 ARCMINUTES</ul></div>
<div style="text-align: center;">&nbsp;</div>

<div>Go to <a  onclick="window.open(this.href,'','resizable=yes,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=no,dependent=no,width=825,height=725,left=100,top=50,status'); return false"  href="/101lab/portal/virtobs/index_trial.html">Virtual Observatory</a>.</div>

<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<p>&nbsp;</p>