<div>The galaxy in which we live is called the Milky Way galaxy. The pictures below show what we think it would look like if we could see from the outside.</div>
<div>&nbsp;</div>
<div style="text-align: center;"><img src="userfiles/image/lab10/wetrans.gif" class="lab" alt="" /><img src="userfiles/image/lab10/mw1.gif" class="lab" alt="" /></div>
<div style="text-align: center;"><img src="userfiles/image/lab10/mw2.gif" class="lab" alt="" /></div>
<div>&nbsp;</div>

<div style="text-align: center;"><a href="userfiles/image/lab10/MilkyWayGalaxy-EdgeView.jpg"><img src="userfiles/image/lab10/MilkyWayGalaxy-EdgeView_small.jpg" class="lab" alt="Milky Way Galaxy envisioned from the edge" /></a></div>
<div>&nbsp;</div>
<div>The above images also show our location within the Milky Way. Where we are in the galaxy determines what we see.</div>
<div>&nbsp;</div>
<div>From studies like the previous exercise you have just done, we've found that globular clusters are very old, much older than the open clusters. This means that they formed much earlier in the history of the Milky Way. In fact, the globular clusters formed around the time the entire galaxy was forming from the merging of many small clouds of gas and &quot;dark matter&quot;. The open clusters formed later (and are still forming) in the disk of the Galaxy. Since the galaxy had a different shape when the globular clusters formed the globular clusters are distributed quite differently in space compared to the open clusters. To investigate this difference you will use the interactive exercise below to plot the positions of open and globular clusters on a grid based on the Galactic Coordinate system.</div>
<div>&nbsp;</div>
<div><a href="http://sci2.esa.int/interactive/media/applets/3_1_1.htm">Explore this applet</a> of our galaxy.  Rotate the galaxy so you can see it on edge and check out the location of the different types of star clusters relative to the disk of the galaxy.</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]<span class="turq"><br />
</span></div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<p>&nbsp;</p>