<div>In this part of the lab, we will be looking at a simulation of the evolution of stars as they leave the Main Sequence. It is recommended that you use 500 stars.  Be aware that it only shows the evolution of a star through the middle of its Red Giant phase.  Also ignore the gap in the Main Sequence that forms at late times near a temperature of about 6300 K.  While you are viewing, pay attention to the following questions:</div>
<div>&nbsp;</div>
<ul>
    <li>Which stars leave the main sequence first?</li>
    <li>What does the H-R diagram look like when a few stars evolve off it? What does it look like when many stars evolve off it?</li>
    <li>How does the shape of the points on the H-R diagram tell us about age?</li>
</ul>
<div>&nbsp;</div>
<div>You can measure the properties of any star by clicking on it. You'll be using these properties when answering questions about stellar temperature, luminosity, mass and cluster age.  The star's Main Sequence lifetime is one number reported.</div>
<div>&nbsp;</div>
<div><a onclick="window.open(this.href,'','resizable=yes,location=no,menubar=no,scrollbars=yes,status=no,toolbar=no,fullscreen=no,dependent=no,width=900,height=800,left=75,top=25,status'); return false" class="applet" href="userfiles/html/HR.html">Stellar Evolution Simulation</a>    (courtesy of R. Scharein at the University of British Columbia). Look at the Stellar Evolution simulation of an H-R diagram of a star cluster.  First, give the cluster 500 stars. Clicking on an individual star allows you to see the properties of that star. Click on several stars at different locations in the diagram.</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>Now click on evolve.  Stop the simulation at three times: when stars of temperature 10,000 K, 7000 K and 6000 K are just leaving the Main Sequence.  In each case, click on such a star and record its mass, luminosity and Main Sequence lifetime.</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<hr />
<div>&nbsp;</div>
<div><span class="violet"><strong>Main Sequence Turn-Off Point</strong></span></div>
<div>&nbsp;</div>
<div>As you just saw in the simulation, the H-R diagram looked different at different times. When astronomers look at the H-R diagrams of star clusters, they also see different patterns. The H-R diagram of a cluster can tell astronomers how old it is.</div>
<div>&nbsp;</div>
<div>Look at the H-R Diagram below of the Hyades open cluster and identify the Main Sequence and the Red Giants: &nbsp;</div>
<div>&nbsp;</div>
<div style="text-align: center;">&nbsp;<img alt="" class="lab" src="userfiles/image/lab10/hyadeshrnew.gif" /></div>
<div>&nbsp;</div>
<div>This should look similar to something you saw in the simulation. Notice the top end of the Main Sequence. The point on the graph where the Main Sequence ends is called the &quot;Main Sequence Turn-off Point.&quot; This is where a star is no longer fusing hydrogen in its core. The Main Sequence turn-off point is indicative of the age of the star cluster. The older a cluster is, the farther down the Main Sequence the turn off point will be. By matching the turn-off point in the simulation with the turn-off point you see in this graph, you can estimate the age of the Hyades.  Don't forget to do this by pausing the simulation and clicking on stars that are just turning off, rather than relying on the ticker.</div>
<div>&nbsp;</div>
<div>[%problem%]</div>
<div>&nbsp;</div>
<p>&nbsp;</p>